#ifndef _COMM_TYPES_H_
#define _COMM_TYPES_H_

#define FRAME_SHBUF_NAME "/shframe"

typedef struct _udsunimsg
{
	unsigned char proto;
	unsigned char title;
	unsigned char type;
	unsigned char size;
} UdsUniMsg;

typedef enum
{
	EYEMETER_ROLE_NONE = 0,
	EYEMETER_ROLE_GUI = 1,
	EYEMETER_ROLE_AI = 2,
	EYEMETER_ROLE_CAM = 3,
	EYEMETER_ROLE_ALL = 0xFF
} EyeMeterRoles;

typedef enum
{
	UDSUNI_PROTO_PTTS4 = 0xAF
} UdsUniProto;

typedef enum
{
	USDUNI_TITLE_STREAM_START = 0x10,
	USDUNI_TITLE_STREAM_RUNNING = 0x12,
	USDUNI_TITLE_STREAM_STOP = 0x1A,

	USDUNI_TITLE_MEAS_START = 0x20,
	USDUNI_TITLE_MEAS_RUNNING = 0x22,
	USDUNI_TITLE_MEAS_SHOOT_DONE = 0x24,
	USDUNI_TITLE_MEAS_RESULT = 0x26,
	USDUNI_TITLE_MEAS_STOP = 0x2A,

	UDSUNI_TITLE_FRAME_READY = 0x30,
	UDSUNI_TITLE_FRAME_BUSY = 0x32,
	UDSUNI_TITLE_FRAME_PROCESSED = 0x34,
	UDSUNI_TITLE_FRAME_FREE = 0x36,

	UDSUNI_TITLE_LED_PWR = 0x40
} UdsUniTitle;

typedef enum
{
	UDSUNI_TYPE_CHAR = 0x00,	// 8 bit. If size > 1 - it is char array
	UDSUNI_TYPE_INT = 0x01,		// usually 32 bits
	UDSUNI_TYPE_FLOAT = 0x2,	// float 32

	UDSUNI_TYPE_SHARED_FRAME = 0x10,
	USDUNI_TYPE_STREAM_SETTINGS = 0x11,
	USDUNI_TYPE_MEASURE_SETTINGS = 0x12,

	USDUNI_TYPE_UNKNOWN = 0xFF
} UdsUniType;

#endif //_COMM_TYPES_H_
