#ifndef _LED_TYPES_H_
#define _LED_TYPES_H_

#define LED_DEFAULT_SEG_NUM 6
#define LED_DEFAULT_ALL_PER_CYCLE 2
#define LED_DEFAULT_POS_PER_CYCLE (LED_DEFAULT_SEG_NUM + LED_DEFAULT_ALL_PER_CYCLE)
#define LED_DEFAULT_CYCLE_NUM 5
#define LED_DEFAULT_POS_NUM (LED_DEFAULT_POS_PER_CYCLE * LED_DEFAULT_CYCLE_NUM)
#define LED_DEFAULT_PWM_ALL 0.16
#define LED_DEFAULT_PWM_ONE 0.96

typedef enum
{
	LED_BYTE_CMD_OFF = 0,
	LED_BYTE_CMD_1 = 1,
	LED_BYTE_CMD_2 = 2,
	LED_BYTE_CMD_3 = 3,
	LED_BYTE_CMD_4 = 4,
	LED_BYTE_CMD_5 = 5,
	LED_BYTE_CMD_6 = 6,
	LED_BYTE_CMD_ALL = 0xF,
	LED_BYTE_CMD_TRIG = 0x1E,
	LED_BYTE_CMD_BLINK_OFF = 0x20,
	LED_BYTE_CMD_BLINK_ON = 0x21,
	LED_BYTE_CMD_DISP_PWR_ON = 0x40
} LED_BYTE_CMDS;

typedef enum
{
	LED_BYTE_ANS_OK = 0x0A,
	LED_BYTE_ANS_FAIL = 0x0E
} LED_BYTE_ANSS;

#endif //_LED_TYPES_H_
