
EYEMETER_ROLE_NONE = 0
EYEMETER_ROLE_GUI = 1
EYEMETER_ROLE_AI = 2
EYEMETER_ROLE_CAM = 3
EYEMETER_ROLE_ALL = 0xFF

FRAME_SHBUF_NAME = "/shframe"

UDSUNI_PROTO_PTTS4 = 0xAF

# Titles
UDSUNI_TITLE_STREAM_START = 0x10
UDSUNI_TITLE_STREAM_RUNNING = 0x12
UDSUNI_TITLE_STREAM_STOP = 0x1A

UDSUNI_TITLE_MEAS_START = 0x20
UDSUNI_TITLE_MEAS_RUNNING = 0x22
UDSUNI_TITLE_MEAS_SHOOT_DONE = 0x24
UDSUNI_TITLE_MEAS_RESULT = 0x26
UDSUNI_TITLE_MEAS_STOP = 0x2A

UDSUNI_TITLE_FRAME_READY = 0x30
UDSUNI_TITLE_FRAME_BUSY = 0x32
UDSUNI_TITLE_FRAME_PROCESSED = 0x34
UDSUNI_TITLE_FRAME_FREE = 0x36

UDSUNI_TITLE_LED_PWR = 0x40


# Types
UDSUNI_TYPE_CHAR = 0x00	# 8 bit. If size > 1 - it is char array
UDSUNI_TYPE_INT = 0x01 # usually 32 bits
UDSUNI_TYPE_FLOAT = 0x2 # float 32

UDSUNI_TYPE_SHARED_FRAME = 0x10
UDSUNI_TYPE_STREAM_SETTINGS = 0x11
UDSUNI_TYPE_MEASURE_SETTINGS = 0x12

UDSUNI_TYPE_UNKNOWN = 0xFF
